// Auto-generated by RustF #[auto_discover] macro - DO NOT EDIT
// This file exists ONLY for IDE support - NOT imported by main.rs
// modules module declarations for autocomplete

#[path = "modules/simple_util.rs"]
pub mod simple_util;
#[path = "modules/payment_service.rs"]
pub mod payment_service;
#[path = "modules/email_service.rs"]
pub mod email_service;
#[path = "modules/string_helpers.rs"]
pub mod string_helpers;
