// Auto-generated by RustF #[auto_discover] macro - DO NOT EDIT
// This file exists ONLY for IDE support - NOT imported by main.rs
// modules module declarations for autocomplete

#[path = "modules/task_lists_service.rs"]
pub mod task_lists_service;
#[path = "modules/auth_service.rs"]
pub mod auth_service;
#[path = "modules/tasks_service.rs"]
pub mod tasks_service;
