// Auto-generated by RustF #[auto_discover] macro - DO NOT EDIT
// This file exists ONLY for IDE support - NOT imported by main.rs
// models module declarations for autocomplete

#[path = "models/users.rs"]
pub mod users;
